language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby
  - jruby-19mode
  - rbx
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: rbx-19mode

services: mongodb
